// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    DatePicker: typeof import('@vuepic/vue-datepicker')['DatePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Icon:bx:clipboard': typeof import('~icons/bx/clipboard')['default']
    'Icon:bx:copy': typeof import('~icons/bx/copy')['default']
    'Icon:bx:mail': typeof import('~icons/bx/mail')['default']
    'Icon:bx:plusCircle': typeof import('~icons/bx/plus-circle')['default']
    'Icon:bx:user': typeof import('~icons/bx/user')['default']
    'Icon:bxs:envelope': typeof import('~icons/bxs/envelope')['default']
    'Icon:bxs:envelopeOpen': typeof import('~icons/bxs/envelope-open')['default']
    'Icon:bxs:plusCircle': typeof import('~icons/bxs/plus-circle')['default']
    'Icon:bxs:userAccount': typeof import('~icons/bxs/user-account')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
