import { $http } from '.';

// Generated by https://quicktype.io

export interface Domains {
    'hydra:member': HydraMember[];
    'hydra:totalItems': number;
    'hydra:view': { [key: string]: string };
    'hydra:search': HydraSearch;
}

export interface HydraMember {
    '@id': string;
    '@type': string;
    '@context': string;
    id: string;
    domain: string;
    isActive: boolean;
    isPrivate: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface HydraSearch {
    '@type': string;
    'hydra:template': string;
    'hydra:variableRepresentation': string;
    'hydra:mapping': HydraMapping[];
}

export interface HydraMapping {
    '@type': string;
    variable: string;
    property: string;
    required: boolean;
}

export class DomainServices {
    static all() {
        return $http.get<Domains>(`/domains`);
    }
}
